#!/usr/bin/env node
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { pathToFileURL } from "node:url";
import { hash } from "@node-rs/argon2";

const AUTH_HASH_KEY = "OMNIHARNESS_AUTH_PASSWORD_HASH";
const AUTH_PASSWORD_KEY = "OMNIHARNESS_AUTH_PASSWORD";
const AUTH_PASSWORD_NOTICE_FILE_KEY = "OMNIHARNESS_AUTH_PASSWORD_NOTICE_FILE";
const ANSI_BOLD_RED = "\u001b[1;31m";
const ANSI_RESET = "\u001b[0m";
const ARGON_OPTIONS = {
  algorithm: 2,
  memoryCost: 19_456,
  timeCost: 2,
  parallelism: 1,
  outputLen: 32,
};

function normalizeEnvValue(value) {
  let normalized = value.trim();
  if (
    (normalized.startsWith("\"") && normalized.endsWith("\"")) ||
    (normalized.startsWith("'") && normalized.endsWith("'"))
  ) {
    normalized = normalized.slice(1, -1);
  }
  return normalized.trim();
}

export function envTextHasConfiguredAuth(envText) {
  for (const line of envText.split(/\r?\n/g)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }

    const match = trimmed.match(/^(?:export\s+)?(OMNIHARNESS_AUTH_PASSWORD(?:_HASH)?)\s*=\s*(.*)$/);
    if (match && normalizeEnvValue(match[2] ?? "")) {
      return true;
    }
  }

  return false;
}

export function hasConfiguredAuth(env = process.env, envPath = path.resolve(".env")) {
  if (env[AUTH_HASH_KEY]?.trim() || env[AUTH_PASSWORD_KEY]?.trim()) {
    return true;
  }

  try {
    return envTextHasConfiguredAuth(fs.readFileSync(envPath, "utf8"));
  } catch (error) {
    if (error?.code === "ENOENT") {
      return false;
    }
    throw error;
  }
}

export function escapeEnvValueForDotenv(value) {
  return value.replace(/\\/g, "\\\\").replace(/\$/g, "\\$").replace(/\n/g, "\\n");
}

export function generatePassword() {
  return crypto.randomBytes(24).toString("base64url");
}

async function promptHidden(input, output, message) {
  if (!input?.isTTY || !output?.isTTY) {
    return null;
  }

  return new Promise((resolve, reject) => {
    const wasRaw = input.isRaw;
    let value = "";

    function restoreInput() {
      input.off("data", onData);
      input.setRawMode(wasRaw);
      input.pause?.();
      output.write("\n");
    }

    function finish(result) {
      restoreInput();
      resolve(result);
    }

    function onData(chunk) {
      const text = String(chunk);
      for (const char of text) {
        if (char === "\u0003") {
          restoreInput();
          reject(new Error("Authentication setup cancelled."));
          return;
        }
        if (char === "\r" || char === "\n") {
          finish(value);
          return;
        }
        if (char === "\u007f" || char === "\b") {
          value = value.slice(0, -1);
          continue;
        }
        if (char >= " ") {
          value += char;
        }
      }
    }

    output.write(message);
    input.setEncoding("utf8");
    input.setRawMode(true);
    input.resume();
    input.on("data", onData);
  });
}

function appendAuthHash(envPath, passwordHash) {
  fs.mkdirSync(path.dirname(envPath), { recursive: true });
  const existing = fs.existsSync(envPath) ? fs.readFileSync(envPath, "utf8") : "";
  const prefix = existing && !existing.endsWith("\n") ? "\n" : "";
  const block = [
    "# OmniHarness web login password. Generated by ./omniharness.",
    `${AUTH_HASH_KEY}=${escapeEnvValueForDotenv(passwordHash)}`,
    "",
  ].join("\n");

  fs.appendFileSync(envPath, `${prefix}${block}`, { mode: 0o600 });
  fs.chmodSync(envPath, 0o600);
}

function formatGeneratedPasswordNotice(password, envPath) {
  return [
    `${ANSI_BOLD_RED}============================================================${ANSI_RESET}`,
    `${ANSI_BOLD_RED}OmniHarness generated your web login password${ANSI_RESET}`,
    "",
    `${ANSI_BOLD_RED}Password: ${password}${ANSI_RESET}`,
    "",
    `${ANSI_BOLD_RED}Save this now. It is shown only once.${ANSI_RESET}`,
    `Stored: ${envPath} contains ${AUTH_HASH_KEY}`,
    `${ANSI_BOLD_RED}============================================================${ANSI_RESET}`,
    "",
  ].join("\n");
}

function writeGeneratedPasswordNotice(output, env, password, envPath) {
  const noticeFile = env[AUTH_PASSWORD_NOTICE_FILE_KEY]?.trim();
  const notice = formatGeneratedPasswordNotice(password, envPath);
  if (!noticeFile) {
    output.write(`\n${notice}\n`);
    return;
  }

  fs.mkdirSync(path.dirname(noticeFile), { recursive: true });
  fs.writeFileSync(noticeFile, notice, { mode: 0o600 });
  fs.chmodSync(noticeFile, 0o600);
}

function printCustomPasswordSaved(output, envPath) {
  output.write(`\n`);
  output.write(`OmniHarness saved your web login password hash in ${envPath}.\n`);
  output.write(`Use the password you entered when the browser login page opens.\n\n`);
}

export async function ensureAuthConfig(options = {}) {
  const rootDir = options.rootDir ?? process.cwd();
  const env = options.env ?? process.env;
  const envPath = options.envPath ?? path.join(rootDir, ".env");
  const input = options.input ?? process.stdin;
  const output = options.output ?? process.stdout;

  if (hasConfiguredAuth(env, envPath)) {
    return { created: false, envPath };
  }

  output.write(`\n[omniharness] Web authentication is required before OmniHarness starts.\n`);
  output.write(`[omniharness] Create a password now, or press Enter to generate a strong one.\n\n`);

  const enteredPassword = options.password ?? await promptHidden(
    input,
    output,
    "OmniHarness web password (leave blank to generate): ",
  );
  const password = enteredPassword?.trim() || options.generatedPassword || generatePassword();
  const generated = !enteredPassword?.trim();
  const passwordHash = await hash(password, ARGON_OPTIONS);

  appendAuthHash(envPath, passwordHash);

  if (generated) {
    writeGeneratedPasswordNotice(output, env, password, envPath);
  } else {
    printCustomPasswordSaved(output, envPath);
  }

  return { created: true, generated, password, envPath };
}

async function main() {
  const rootDir = process.cwd();
  const envPath = process.env.OMNIHARNESS_AUTH_ENV_FILE
    ? path.resolve(process.env.OMNIHARNESS_AUTH_ENV_FILE)
    : path.join(rootDir, ".env");

  await ensureAuthConfig({ rootDir, envPath });
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    process.stderr.write(`[omniharness] ${error instanceof Error ? error.message : String(error)}\n`);
    process.exit(1);
  });
}
